### PR TITLE
Check header CRC

### PR DESCRIPTION
**Pull request by alfredosola**
Added the CRC check function from https://danielwippermann.github.io/resol-vbus/vbus-specification.html to check header CRC (and removed TODO comment)

### CODE REVIEW

**Review by FatBeard — COMMENTED** [review]
Thanks for PR. I notice occasionally I get an erroneous figure from the vbus. I'm guessing this would solve that problem?

**Comment by alfredosola** [comment]
> Thanks for PR. I notice occasionally I get an erroneous figure from the vbus. I'm guessing this would solve that problem?

In my experience, erroneous readings from vBus can happen if something is wrong with the controller. To be honest, I have added CRC checking as a troubleshooting step to isolate the cause of noise in one of my sensors, and I thought I could as well add it to the library because it is nice to have.

In this PR only the header is checked, but I'll look into adding checks for the information frames too.

Try it out, see if this solves your errors.

**Comment by FatBeard** [comment]
Thanks, i'll give it a try. To be honest it's possibly one read in about 40 or 50 thousand so this might do the trick. I only notices it as it skews my graphs when looking over a few days.

**Comment by FatBeard** [comment]
I've merged it but there were compilation issues. Can you double check my changes look good. I'll test myself over the next few days.

**Comment by alfredosola** [comment]
Looking good to me.

Sorry I missed including the function in the base class. I don’t really understand why the compiler doesn’t like const *Buffer, but the const is only there to underline that the function doesn’t change it, so while it’s nice to have, removing it won’t break anything.

Thanks!

**Pull request merged**
